---
- name: Download and unarchive node_exporter.
  ansible.builtin.unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: /tmp
    remote_src: true
    mode: 0755

- name: Move node_exporter binary into place.
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}/node_exporter"
    dest: "{{ node_exporter_bin_path }}"
    mode: 0755
    remote_src: true

- name: Create node_exporter user.
  ansible.builtin.user:
    name: node_exporter
    shell: /sbin/nologin
    state: present

- name: Copy the node_exporter systemd unit file.
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644

- name: Reload systemd daemon if unit file is changed.
  ansible.builtin.systemd:
    daemon_reload: true
    name: node_exporter
    state: restarted

- name: Ensure node_exporter is running and enabled at boot.
  ansible.builtin.service:
    name: node_exporter
    state: "{{ node_exporter_state }}"
    enabled: "{{ node_exporter_enabled }}"
  when: not ansible_check_mode

- name: Verify node_exporter is responding to requests.
  ansible.builtin.uri:
    url: "http://{{ node_exporter_host }}:{{ node_exporter_port }}/"
    return_content: true
  register: metrics_output
  failed_when: "'Metrics' not in metrics_output.content"
